version: '3.8'

services:
  web:
    build: .
    container_name: property_research_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=property_research
      - DB_USER=property_user
      - DB_PASS=property_password
    networks:
      - property_network

  db:
    image: mysql:8.0
    container_name: property_research_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=property_research
      - MYSQL_USER=property_user
      - MYSQL_PASSWORD=property_password
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - property_network

volumes:
  db_data:

networks:
  property_network:
    driver: bridge
